@include('includes.html.begin')
@include('includes.html.head')
@include('includes.html.body-begin')
@include('includes.wechat-icon')
@include('includes.client')
@yield('body')
@stack('js')
@include('includes.alerts')
@include('includes.baidu-analytics')
@include('includes.html.end')

